GET http://bangazon.com:5000/api/trainingProgram
###

POST http://bangazon.com:5000/api/trainingProgram
Content-Type: application/json

{
    "name": "Test2",
    "startDate": "12/19/2018",
    "endDate": "12/20/2018",
    "maxAttendance": "10"
}
###